[package]
name = "opentyde"
version = "0.1.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nom = "5.0"
petgraph = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.3"
wasm-bindgen = "0.2"
